import type { AppTheme, AppThemeId, ThemeColors } from '@/lib/themes/types';

export const DEFAULT_THEME_ID: AppThemeId = 'wired-original';

const wiredColors: ThemeColors = {
  bg: '#FFFFFF',
  bg2: '#F5F5F7',
  surface: '#FFFFFF',
  surfaceSubtle: '#FBFBFD',
  border: '#E8E8ED',
  borderStrong: '#D2D2D7',
  ink: '#1D1D1F',
  secondary: '#6E6E73',
  tertiary: '#A1A1A6',
  accent: '#FF6A2B',
  accentSoft: '#FFF1EA',
  accentDark: '#E55A1F',
  accentLight: '#FF8F5C',
  blue: '#0071E3',
  blueSoft: '#E8F1FD',
  green: '#34C759',
  greenSoft: '#E8F8EC',
  amber: '#FF9F0A',
  amberSoft: '#FFF6E5',
  purple: '#AF52DE',
  red: '#FF3B30',
  tabBarBg: 'rgba(255,255,255,0.92)',
};

export const APP_THEMES: AppTheme[] = [
  {
    id: 'wired-original',
    name: 'Wired Original',
    tagline: 'Clean white & signature orange',
    emoji: '⚡',
    colors: wiredColors,
    statusBar: 'dark',
    borderRadius: { card: 18, button: 12 },
    typography: {
      scale: { body: 1, caption: 1, heading: 1, title: 1 },
      letterSpacing: { body: 0, heading: -0.3 },
      displayFont: true,
    },
  },
  {
    id: 'off-road',
    name: 'Off-road',
    tagline: 'Trail dust, olive drab & mud orange',
    emoji: '🏜️',
    colors: {
      bg: '#FAF6EF',
      bg2: '#EDE4D4',
      surface: '#FFFCF7',
      surfaceSubtle: '#F7F1E6',
      border: '#C9BCA5',
      borderStrong: '#A8987E',
      ink: '#2C3E2A',
      secondary: '#5C6B52',
      tertiary: '#8A9680',
      accent: '#C45C26',
      accentSoft: '#F5E6D3',
      accentDark: '#9E4518',
      accentLight: '#E07A3A',
      blue: '#4A6741',
      blueSoft: '#E8EFE4',
      green: '#6B8E23',
      greenSoft: '#EDF3E0',
      amber: '#D4A017',
      amberSoft: '#F9F0D4',
      purple: '#7A6B5D',
      red: '#B83227',
      tabBarBg: 'rgba(250,246,239,0.94)',
    },
    statusBar: 'dark',
    borderRadius: { card: 14, button: 10 },
    typography: {
      scale: { body: 1.02, caption: 0.98, heading: 1.06, title: 1.1 },
      letterSpacing: { body: 0.2, heading: 0.8 },
      displayFont: true,
    },
  },
  {
    id: 'track',
    name: 'Track',
    tagline: 'Asphalt grey, racing red & caution yellow',
    emoji: '🏁',
    colors: {
      bg: '#F2F2F4',
      bg2: '#E4E4E8',
      surface: '#FFFFFF',
      surfaceSubtle: '#F8F8FA',
      border: '#C8C8D0',
      borderStrong: '#9898A4',
      ink: '#0A0A0C',
      secondary: '#4A4A52',
      tertiary: '#787880',
      accent: '#E10600',
      accentSoft: '#FFE8E6',
      accentDark: '#B00500',
      accentLight: '#FF3B30',
      blue: '#1E3A5F',
      blueSoft: '#E3EBF5',
      green: '#00843D',
      greenSoft: '#E0F5EA',
      amber: '#FFD000',
      amberSoft: '#FFF8CC',
      purple: '#5C4B8A',
      red: '#E10600',
      tabBarBg: 'rgba(242,242,244,0.95)',
    },
    statusBar: 'dark',
    borderRadius: { card: 12, button: 8 },
    typography: {
      scale: { body: 0.98, caption: 0.92, heading: 1.1, title: 1.14 },
      letterSpacing: { body: 0, heading: 1.2 },
      displayFont: true,
    },
  },
  {
    id: 'jdm',
    name: 'JDM',
    tagline: 'Midnight purple, neon pink & cyan glow',
    emoji: '🌃',
    colors: {
      bg: '#0D0B14',
      bg2: '#16121F',
      surface: '#1E1830',
      surfaceSubtle: '#14101E',
      border: '#2A2540',
      borderStrong: '#3D3560',
      ink: '#F5F0FF',
      secondary: '#B8AED0',
      tertiary: '#7A7094',
      accent: '#FF2D95',
      accentSoft: '#3D1F35',
      accentDark: '#CC2478',
      accentLight: '#FF5CAD',
      blue: '#00F0FF',
      blueSoft: '#0A2A30',
      green: '#39FF14',
      greenSoft: '#152818',
      amber: '#FFE600',
      amberSoft: '#2A2810',
      purple: '#9D4EDD',
      red: '#FF006E',
      tabBarBg: 'rgba(13,11,20,0.96)',
    },
    statusBar: 'light',
    borderRadius: { card: 16, button: 10 },
    typography: {
      scale: { body: 0.95, caption: 0.9, heading: 1.05, title: 1.08 },
      letterSpacing: { body: 0.3, heading: 2 },
      displayFont: true,
    },
  },
  {
    id: 'muscle',
    name: 'Muscle',
    tagline: 'Cherry red, chrome gold & bold Americana',
    emoji: '💪',
    colors: {
      bg: '#FFF8F0',
      bg2: '#F5EBE0',
      surface: '#FFFFFF',
      surfaceSubtle: '#FFF5EB',
      border: '#D4C4B0',
      borderStrong: '#B8A090',
      ink: '#1A0A0A',
      secondary: '#5C4033',
      tertiary: '#8B7355',
      accent: '#CC0000',
      accentSoft: '#FFE5E5',
      accentDark: '#990000',
      accentLight: '#E63333',
      blue: '#1A237E',
      blueSoft: '#E8EAF6',
      green: '#2E7D32',
      greenSoft: '#E8F5E9',
      amber: '#D4AF37',
      amberSoft: '#FFF8E1',
      purple: '#6A1B9A',
      red: '#CC0000',
      tabBarBg: 'rgba(255,248,240,0.94)',
    },
    statusBar: 'dark',
    borderRadius: { card: 10, button: 8 },
    typography: {
      scale: { body: 1.05, caption: 1, heading: 1.2, title: 1.25 },
      letterSpacing: { body: 0.1, heading: 0.5 },
      displayFont: true,
    },
  },
  {
    id: 'euro',
    name: 'Euro',
    tagline: 'Alpine blue, silver grey & refined lines',
    emoji: '🇪🇺',
    colors: {
      bg: '#F8F9FB',
      bg2: '#EEF1F5',
      surface: '#FFFFFF',
      surfaceSubtle: '#FAFBFC',
      border: '#D8DEE6',
      borderStrong: '#B0BAC8',
      ink: '#1C2530',
      secondary: '#5A6578',
      tertiary: '#8892A0',
      accent: '#0066B3',
      accentSoft: '#E3EEF8',
      accentDark: '#004D87',
      accentLight: '#3388CC',
      blue: '#0066B3',
      blueSoft: '#E3EEF8',
      green: '#2E7D5A',
      greenSoft: '#E6F4ED',
      amber: '#C9A227',
      amberSoft: '#F5F0E0',
      purple: '#5E548E',
      red: '#C0392B',
      tabBarBg: 'rgba(248,249,251,0.95)',
    },
    statusBar: 'dark',
    borderRadius: { card: 16, button: 12 },
    typography: {
      scale: { body: 0.98, caption: 0.94, heading: 1, title: 1.05 },
      letterSpacing: { body: 0.15, heading: 0.3 },
      displayFont: false,
    },
  },
  {
    id: 'race',
    name: 'Race',
    tagline: 'Carbon black, fluorescent lime & pit lane',
    emoji: '🏎️',
    colors: {
      bg: '#0C0C0E',
      bg2: '#141418',
      surface: '#1A1A1F',
      surfaceSubtle: '#101014',
      border: '#2A2A32',
      borderStrong: '#3A3A44',
      ink: '#FFFFFF',
      secondary: '#A0A0A8',
      tertiary: '#6B6B75',
      accent: '#D4FF00',
      accentSoft: '#2A2F00',
      accentDark: '#A8CC00',
      accentLight: '#E5FF4D',
      blue: '#00A3FF',
      blueSoft: '#0A1F30',
      green: '#D4FF00',
      greenSoft: '#1A1F00',
      amber: '#FFAA00',
      amberSoft: '#2A2000',
      purple: '#BF5AF2',
      red: '#FF0040',
      tabBarBg: 'rgba(12,12,14,0.96)',
    },
    statusBar: 'light',
    borderRadius: { card: 14, button: 10 },
    typography: {
      scale: { body: 0.97, caption: 0.9, heading: 1.12, title: 1.16 },
      letterSpacing: { body: 0.5, heading: 1.5 },
      displayFont: true,
    },
  },
];

const themeMap = new Map(APP_THEMES.map((t) => [t.id, t]));

export function getThemeById(id: AppThemeId): AppTheme {
  return themeMap.get(id) ?? themeMap.get(DEFAULT_THEME_ID)!;
}

export function isAppThemeId(value: string): value is AppThemeId {
  return themeMap.has(value as AppThemeId);
}
